Fix (GH actions): Improving workflows

diff --git a/.github/workflows/stage-deck-change.yaml b/.github/workflows/stage-deck-change.yaml
--- a/.github/workflows/stage-deck-change.yaml
+++ b/.github/workflows/stage-deck-change.yaml
@@ -159,8 +159,19 @@ jobs:
           #  See: https://docs.github.com/en/actions/using-workflows/workflow-commands-for-github-actions#example-of-a-multiline-string
           EOF=$(dd if=/dev/urandom bs=15 count=1 status=none | base64)
           echo "DIFF<<$EOF" >> $GITHUB_ENV
+          
+          # Temporarily allow failures
+          set +e
           deck gateway diff --konnect-control-plane-name "$CONTROL_PLANE_NAME" --konnect-token "$KONNECT_PAT" "$FILE_PATH" >> $GITHUB_ENV
+          STATUS=$?
+          set -e
+          
+          # Always append the EOF marker, regardless of the diff command's success
           echo "$EOF" >> $GITHUB_ENV
+          if [[ $STATUS -ne 0 ]]; then
+            echo "::error::Failed to run deck diff"
+            exit $STATUS
+          fi
 
       - name: Create PR for changes
         uses: peter-evans/create-pull-request@v5
